# Modifier and Vim-style direction keys.
set $mod Mod4
set $left h
set $down j
set $up k
set $right l

# Applications. Requires foot and rofi-wayland.
set $term foot
set $rofi_cmd rofi \
        -terminal '$term'
set $menu $rofi_cmd -show combi -combi-modes drun#run -modes combi
