# Modifier and Vim-style direction keys.
set $mod Mod4
# set $left h
# set $down j
# set $up k
# set $right l

# Applications and Quickshell controls.
set $term foot
set $browser brave-browser
set $herdr herdr
set $menu quickshell ipc call launcher toggle
set $keybindings quickshell ipc call keybindings toggle
set $notification_center quickshell ipc call notification-center toggle
set $power_menu quickshell ipc call power-menu toggle
