# Modifier and Vim-style direction keys.
set $mod Mod4
# set $left h
# set $down j
# set $up k
# set $right l

# Applications. Requires Foot and Quickshell.
set $term foot
set $menu quickshell ipc call launcher toggle
set $keybindings quickshell ipc call keybindings toggle
