# Lock after 10 minutes of inactivity and suspend after 15 minutes.
exec swayidle -w \
    timeout 600 'gtklock --daemonize' \
    timeout 900 'systemctl suspend' \
    before-sleep 'gtklock --daemonize'
