# Navigate workspaces with three-finger horizontal swipes.
bindgesture --exact swipe:3:right exec ~/.config/sway/scripts/swipe-workspace previous
bindgesture --exact swipe:3:left exec ~/.config/sway/scripts/swipe-workspace next
