# Override Fedora's Swaylock-based idle fragment with Gtklock.
exec swayidle -w \
    timeout 600 'gtklock --daemonize' \
    timeout 900 'systemctl suspend' \
    before-sleep 'gtklock --daemonize' \
    lock 'gtklock --daemonize'
