# Override Fedora's Swaylock-based idle fragment with Gtklock.
exec swayidle -w \
    timeout 600 '~/.config/gtklock/lock --daemonize' \
    timeout 900 'systemctl suspend' \
    before-sleep '~/.config/gtklock/lock --daemonize' \
    lock '~/.config/gtklock/lock --daemonize'
