#!/usr/bin/env bash

set -euo pipefail

config_dir="$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" && pwd)"

exec gtklock \
    --config "$config_dir/config.ini" \
    --style "$config_dir/style.css" \
    --layout "$config_dir/layout.xml" \
    --background "$config_dir/background.png" \
    "$@"
